/**
 * Tree-shaking optimized imports
 * Bu dosya kullanılmayan kodların bundle'a dahil edilmemesini sağlar
 */

// Lucide icons - sadece kullanılanları import et
export {
  Book,
  BookOpen,
  Users,
  Settings,
  LogOut,
  Menu,
  X,
  Search,
  Filter,
  Heart,
  Star,
  Calendar,
  Clock,
  AlertCircle,
  CheckCircle,
  MessageSquare,
  Send,
  Edit,
  Trash2,
  Eye,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Home,
  Library,
  DollarSign,
  Bell,
  User,
  Mail,
  Phone,
  MapPin,
  Image as ImageIcon,
  Upload,
  Download,
  Plus,
  Minus,
  Save,
  RefreshCw,
  MoreVertical,
  ExternalLink,
  Copy,
  Check,
  AlertTriangle,
  Info,
  HelpCircle,
  Loader2,
  BookPlus,
  Target,
  TrendingUp,
  BarChart,
  PieChart,
  Gamepad2,
  Gift,
  Tag,
  Ruler,
  Quote,
  ScrollText,
  BookText,
  UserCog,
  ClipboardList,
  Layers,
  Square,
  CheckSquare,
  History,
  ImageOff,
} from 'lucide-react';

// Date-fns - sadece kullanılan fonksiyonları import et
export { format, formatDistance, formatRelative, subDays, addDays, isAfter, isBefore, differenceInDays } from 'date-fns';

// Chart.js - sadece gerekli componentleri import et
export {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  Filler,
} from 'chart.js';
